export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // This is the layout that wraps all pages
  //Good place to put global styles, header, footer, etc.
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
